### ISSUE TITLE
Container B and D disfunction

### ISSUE THREAD

**Issue by robinleruth** [budlabs/i3ass#39] opened 2018-11-17 00:59 UTC
Hello bud,

First thank you very much for putting all these effort into making an enjoyable tool usable by everyone

I discovered i3ass on reddit and I watched your video, I instantly wanted i3fyra to work on my computer

Unfortunately it doesn't seem to work on my laptop

**INSTALLATION**
I first installed it by cloning this git repo, filling the Makefile with a custom TARGETDIRECTORY (I created a /home/user/bin for customed software)
And then modified my .config/i3/config by using what you told on your video,
 basically for all window -> floating enabled ; mod+shift+space i3fyra -a and then personalizing all other application to open in correct container

**ISSUE**
The family doesn't seem to be created correctly 
Container A and C are working correctly, but B and D are acting suspiciously. They open as Tabbed with the A container and when I stack them manually (mod+e) I lose all the benefits from i3fyra
Also, i3fyra -m left, up and down are working for container A and C but i3fyra -m right is hiding all containers and I am not able to get them back

I first thought it was my config that was perturbing everything so I tried it with the initial config i3 gives us when we first launch it and I have the same behaviour

I also tried to install i3ass from AUR, from dev branch and I tried one commit that was from 2017 ahah

Anyway, thank you for your time and if my issue is not obvious for you, don't take too much time thinking about it
I'll either figure something out or give up ahah
Cheers

**Comment by lukewang1024** [comment] 2018-12-15 06:18
I have experienced similar issue with config that used to work. Perhaps it has something to do with incompatibility between i3 / i3fyra versions. Below are mine:

```bash
~
λ i3fyra -v
i3fyra - version: 0.501
updated: 2018-06-30 by budRich
~
λ i3 -v
i3 version 4.16 (2018-11-04) © 2009 Michael Stapelberg and contributors
```

**Comment by lukewang1024** [comment] 2018-12-15 06:31
And according to [previous issue](https://github.com/budlabs/i3ass/issues/37), downgrading to 4.15 can get it to work till bud fixes the issue:

```bash
pacman -U https://archive.archlinux.org/packages/i/i3-gaps/i3-gaps-4.15.0.1-2-x86_64.pkg.tar.xz
```

**Comment by budRich** [comment] 2019-01-12 05:33
Hi guys, sorry for this very late reply. I hae fixed this issue now. The cause was the following: prior to i3 version 4.16, one could move window to a workspace container specifying the id, the window would then be placed according to the layout of the workspace (just like with any other container). Now however, when one tries to move a container to a workspace with a con_id, the action will be interpreted the same as `move to workspace`, resulting in no action at all if the window already is on the workspace. Whatever it should work now. Thank you guys for testing and reporting and helping each other, i will try to be more active her from now on.

**Closed by budRich** 2019-01-12 05:33 UTC
