### ISSUE TITLE
[i3fyra] Errors with getting i3fyra working

### ISSUE THREAD

**Issue by MatthewCushing** [budlabs/i3ass#37] opened 2018-11-06 09:35 UTC
I originally had i3-gaps and was having this issue so I reinstalled as regular i3 but the issue persists =/.
I have been following your video tutorial on i3-fyra "Let's Lynux #003: I3fyra".  I've gotten to the point where you are writing in the commands to move containers about 15min in.  

When I type in `i3fyra -m left` command I get these errors:
`ERROR: Given criteria don't match a window`
`[ERROR] no matching window.`
`ERROR: Given criteria don't match a window`
`[ERROR] no matching window.`
`ERROR: Given criteria don't match a window`
When I type in:
`i3fyra -m right`
`i3fyra -m up`
`i3fyra -m down`
I get no errors but the window doesn't move either and the titlebar text changes depending on the location I have the window.  In example of what title bar says is:
"MOVE w:1437 h:1038 x:922 y:623"

Now when I actually move to a container in the next step in the video I get a weird result as well.
It's as if it doesn't want to split the containers horizontally.  I get different orientations depending on which order I try and place the containers as well as a 'null' error.  I have uploaded 8 pictures to imgur giving you a "slideshow" type appearance so you can see my steps. First time I do, A, B, C, D and second time I try B, A, D, C and get a null error in container A.  
Link to imgur pictures: https://imgur.com/a/oDUzTdr
As you can see, the containers AC and BD are connected both times.  Depending on the order I do it in, I always get A and B on top and depending on the order C or D on bottom.  If I make A first then B and D will be split together and be stuck in a tab up top where I can tab between A and the B D split with C on the bottom.  If I open B first I get A and C stuck up top in the split that I can tab between with D on the bottom by itself.  Hope this isn't too confusing xD.

The only things I had done so far in your video were to set all windows to open floating as well as ctrl+shift+space fyra setting.  I have a 4k monitor laptop, I hope that has nothing to do with it.  I can post my i3 config if needed.

I really hope we can figure this out, I'll reinstall if I have to :(

**Comment by budRich** [comment] 2018-11-06 18:05
thanks for testing i3fyra. It appears that the latest release of i3 (`4.16`) broke some i3fyra functionality. I have not yet researched this and don't know exactly whats going on, but i will try to figure it out asap (since i use i3fyra myself and really want this to work). 

@mrcush can you confirm your i3 version (`$ i3 -v`)

**Comment by mrcush** [comment] 2018-11-06 21:29
Definitely!
`i3 -v`
`i3 version 4.16 (2018-11-04) © 2009 Michael Stapelberg and contributotors`

Also, I don't know if this bugged from i3fyra or not but:
`i3fyra -a`
when on 2nd+ workspace to put window back into tiled (since set to automatically start floated) sometimes randomly pops my Fifrefox (maybe other applications?) out of tiled and back into floating.  This just happened randomly yesterday several times when I was using Firefox.  It hasn't reproduced since I reinstalled to regular i3wm from i3-gaps though.  
Really appreciate your work for the community!

**Comment by budRich** [comment] 2018-11-06 23:38
yes these new issues are related to the 4.16 release. i3fyra currently have no support for i3gaps, but i just got a "new" computer with a much larger screen, which means that i both can afford gaps (and can start experimenting getting i3fyra working with gaps) and start optimizing i3fyra/ass for multimonitor setups.  

I don't know exactly how long it will take to make i3fyra work well with this new i3 release (i think it will actually work a lot better and faster (i had a hackish way to calculate the size for the containers, which i think is unnecessary now that tiled containers size can be set in pixels not just percentage. I cannot promise anything, but it should be fixed before monday, hopefully before friday.  

If you really want to try i3fyra now, you could downgrade i3 to version 4.15 and it "should work fine".

**Comment by mrcush** [comment] 2018-11-07 00:02
Sounds great. In regards to i3-gaps, I’m personally not worried about it as I had stopped using the gaps and switched over to normal i3wm but figured I’d let you know. I definitely want to use fyra so I’ll downgrade until you update. Just have to figure out how. Thanks!

**Comment by mrcush** [comment] 2019-01-12 07:33
Going to upgrade to 4.16 now!  Thanks for updating!  Any new videos coming up soon?  Lastly, what do you use to theme gtk?  Do you customize the css yourself?  Thanks again!

**Comment by budRich** [comment] 2021-08-10 22:07
sorry for the late reply. im closing this issue, i think everything works fine. i don't like oomox, since it pulls so many dependencies and take forever to build. i just get a nice theme (OneStepBack) and modify the theme files manually. Sometimes I use my own theme-generator thingie called mondo-generator.

**Closed by budRich** 2021-08-10 22:07 UTC
Labels: bug
