### ISSUE TITLE
Division by Zero errors

### ISSUE THREAD

**Issue by pnobre** [budlabs/i3ass#22] opened 2018-08-16 21:03 UTC
Hi, 

Found your i3fyra scripts from your youtube videos and found it really cool. However, when trying to follow, I got some errors when running i3fyra and nothing else happens:

`i3fyra -l 'AB=-370 BD=250 AC=130'`

```
awk: cmd. line:2: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:2: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:2: (FILENAME=- FNR=1) fatal: division by zero attempted
```

I'm running the latest versions of your scripts from this repo, using i3-gaps version 4.15.0.1-2

**Comment by budRich** [comment] 2018-08-17 05:54
Thanks for testing and reporting. I will have a look at this today, i have noticed issues myself that is probably related.  

I think i need to build some kind of test suit for i3fyra.

**Comment by budRich** [comment] 2018-08-17 16:03
@pnobre try the latest release (available both here on gh and in AUR if you use arch), if the issue is resolved: close this issue.

Thank you very much for reporting this, and please let me know if you find more bugs, issues, or have any enhancements ideas. I have not had many testers for i3fyra, so i am very interested in feedback.

**Comment by pnobre** [comment] 2018-08-17 16:25
Sure. Will give it a go tonight and let you know.

P
________________________________

**Comment by budRich** [comment] 2018-09-01 19:58
@pnobre i hope the issue is resolved and I will close it now. But feel free to open again if the issue persists.

**Closed by budRich** 2018-09-01 19:58 UTC
Labels: bug
